### ISSUE TITLE
How can i change style of Jumio .

### ISSUE THREAD

**Issue by sonusaini97** [caseyryan/flutter_jumio#7]
I am using your lib and unable to change style of that like color,theme.
Please Provide feature to do that.

**Comment by caseyryan** [comment]
Hi! This functionality is planned, and I even have some tickets for it but is not supported yet. I needed this library for my job but right now I have different tasks and too much work to do. So I can't say when I will add this. And btw, the styles can only be supported on iOS. Android theme just cannot be changed on the fly as far as I know

**Comment by sonusaini97** [comment]
Hi caseyryan,
Thank you for your reply..
I have read jumio documentation and they provide a method to customize their theme at runtime so why are you not tried that

**netverifySDK.setCustomTheme(CUSTOMTHEME);**

Please complete your sdk it's good for others developers if is it easy to change for you.

**Comment by caseyryan** [comment]
`I have read jumio documentation and they provide a method to customize their theme at runtime so why are you not tried that`

Thanks for this. I'm not really a native android developer, so I didn't dig deeper into that. As I can see there must be a custom xml theme and it's gotta be defined as a resource id. I will definitely not do that because I just don't know how to do it on android and I don't need it for the project. I will implement this for iOS as it does not require any external resources. But if you need a custom theme and you know how to do that, feel free to fork the repo or to create a pull request
