### ISSUE TITLE
 Unable to get scanReference from your provide sdk lib.

### ISSUE THREAD

**Issue by sonusaini97** [caseyryan/flutter_jumio#8]
I have initialize JumioNetverifySdk

    await FlutterJumio.initNetverify(
        apiToken: "******-2405-4828-bee2-952bdc73012a",
        apiSecret: "******6ex5rl86dISCO9hJZoDfTyyK2",
        dataCenter: DataCenter.US,
        config: NetverifyConfig(
          documentTypes: [
            DocumentType.PASSPORT,
            DocumentType.DRIVER_LICENSE,
            DocumentType.IDENTITY_CARD,
            DocumentType.VISA,
          ],
          cameraPosition: CameraPosition.FRONT,
          dataExtractionOnMobileOnly: true,
          enableIdentityVerification: true,
          enableVerification: true,
          preselectedDocumentVariant: PreselectedDocumentVariant.PAPER,
          sendDebugInfoToJumio: true,
          enableWatchlistScreening: EnableWatchlistStreening.DEFAULT,
        )
    );

and called
**var JumioRef = await FlutterJumio.startNetVerify();**
after click a button and waiting for JUMIO Result .
but i did not got any response from Jumio after successfully completed verification.

Please go through and correct me if i'm wrorng.

**Comment by caseyryan** [comment]
Please make sure you use the correct data center and api secret and token are not mixed up (and remove them from here). This feature works fine since I use it myself in my work project.
Also, do you see any jumio ui then you start a netverify? 
If everything is setup correctly, you will see their green views on android and blurred views on ios

p.s. Also make sure you use transaction creation token and secret, not transaction administration ones. It's very important

**Comment by sonusaini97** [comment]
I'm using valid credentials,
Hey caseyryan ,
please confirm 
**var JumioRef = await FlutterJumio.startNetVerify();**
above line is valid line to get **jumio Scan Reference** .

**Comment by caseyryan** [comment]
Yes, it's valid. You don't have to store a reference since the Future does not return anything.
```dart
static Future startNetVerify() async {
    await _sendParams(_Method.StartNetverify, null);
  } 
```
You can simply do this 
await FlutterJumio.startNetVerify();

Please, build an example project with your credentials and launch it. The example project works, I'm totally sure.
